### ISSUE TITLE
Audio latency

### ISSUE THREAD

**Issue by selimgr** [tomodwyer/nodetunes#7]
First, THANK YOU VERY MUCH! I've been searching for a REALLY long time a working nodetunes library. 

When playing audio from a YouTube video, I get ~5ms latency. Is it due to my network or the library?

Please continue your work on this!! Thank you very much!! ❤️

**Comment by tomodwyer** [comment]
Hello - no worries, I'm glad it's working for you. Unfortunately latency seems to be part of the AirPlay protocol ([more info](https://www.reddit.com/r/HomePod/comments/7wnxdu/airplay_latency/du1sjla/)) - so I think the latency you're experiencing is part of that 😢 

When [AirPlay 2](https://developer.apple.com/videos/play/wwdc2017/509/) is finally released, I may be able to push an update that will fix this.
